BaseUrl: "https://zjj2wry.github.io/"
Title: "zhengjiajin's blog"
theme: "beg"
disqusShortname: zhengjiajin
Params:
  Author: "zhengjiajin"
  Github: "zjj2wry"
  ShowRelatedPost: True
  # Disqus: "unresolved"

MetadataFormat: "yaml"
